ALTER TABLE public.courses
ADD COLUMN IF NOT EXISTS weekly_hours INT DEFAULT NULL,
ADD COLUMN IF NOT EXISTS academic_period VARCHAR(50) DEFAULT NULL,
ADD COLUMN IF NOT EXISTS academic_year VARCHAR(20) DEFAULT NULL;
